# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$HOME/bin:$PATH:.

export PATH

export DATA_PATH=/data/mysql/
alias cds="cd $HOME/source"
alias cdb="cd $HOME/build"
alias cdd="cd $DATA_PATH"

alias cddm="cd $DATA_PATH/mysqldemo"

alias cdsm="cd $HOME/source/mysql"
alias cdsmt="cd $HOME/source/mysql-tools"
alias cdbm="cd $HOME/build/mysql"

export CLION_HOME=$HOME/dev/clion/clion2019
export PATH=$CLION_HOME/bin:$PATH:.
alias cdc="cd $CLION_HOME"

alias cdmut="cd $HOME/source/mysql/unittest/gunit/"

alias cddmgr="cd $DATA_PATH/mgrdemo"
alias cddm1="cd $DATA_PATH/mgrdemo/s1"
alias cddm2="cd $DATA_PATH/mgrdemo/s2"
alias cddm3="cd $DATA_PATH/mgrdemo/s3"


alias cddrpl="cd $DATA_PATH/rpldemo"
alias cddr1="cd $DATA_PATH/rpldemo/s1"
alias cddr2="cd $DATA_PATH/rpldemo/s2"
